### ISSUE TITLE
mice:pool(): doesn't work for for censReg/tobit anymore (“No glance method recognized for this list”)

### ISSUE THREAD

**Issue by levi-polsci** [amices/mice#148]
Thanks also from my side for the wonderful mice package.

Unfortunately, since I have updated my version of R to 3.4.4., the mice::pool() function does not work for my censReg object anymore.

I build a mice object using

```
library(mice)
library(censReg)
library(lattice)
set.seed(1234)
m<-matrix(sample(c(NA, 1:10), 100, replace = T), 10) # Create data with NA's
df<-as.data.frame(m) 
df$V1 <- c(1,0,6,0,0,0,3,NA,0,4) # censor V1
imp <- mice(df) # impute object
```

Afterwards, I perform a censored regression analysis of the imputed object and try to pool the results:

```
fit <- with(imp,  censReg(V1 ~ 
                            V2 +
                            V3+
                            V4                              
                           , left = 0
                          , right = Inf))
s1 <- pool(fit)
```

While this was not a problem before I updated my R version, I now get the error code:

```
Error in glance.list(X[[i]], ...) : 
No glance method recognized for this list
```

I tried to use the tobit() function from the AER package instead of censReg, but here I receive a similarly obscure error message:

```
Error in if (!is.null(newnames) && length(newnames) != ncol(x)) { : 
missing value where TRUE/FALSE needed
```

I also tried to recover an older version of R, but for every version earlier than 3.4.0. the censReg installation fails and for every version from 3.4.0. onwards the installation succeeds, but I get the error message mentioned above whenever I try to pool the miced censReg analyses.

Do you know where this bug could come from and how it can be solved?

Thank you very much!

**Comment by gerkovink** [comment]
Dear SebastianL1, 

`mice` uses `broom` to do the pooling since version `3.0`. If you have updated `mice` when updating `R`, chances are you come from an earlier `mice` version; which explains why pooling now expects a different behaviour than before. 

See #121 and #142 for some more detail.

All the best, 

Gerko
