### ISSUE TITLE
Conditional imputation: Two solutions

### ISSUE THREAD

**Issue by angelrodriguez2020** [amices/mice#258]
Dear fellows,

I'm using your excellent package MICE. 

I have two variables that I need to impute together: `caidas` is the number of falls (numeric), and `cq18b` is a variable of the care received by the person who fell; it is a factor with levels 

1. No fall 
2. Medical care received
3. No medical care needed

When imputing `caidas`, I want that if `caidas==0`, `cq18b==1` and if `caidas>0` `cq18b` gets either an imputed  2 or 3. 

This fragment of code limits the second imputation to 3, but I'd like that it imputes 2 or 3, depending on other predictors.

```r
post["cq18b"] <- "
                  imp[[j]][data$caidas[!r[,j]]==0,i] <- levels(tshauprf2$cq18b)[1]
                  imp[[j]][data$caidas[!r[,j]]>0,i] <- levels(tshauprf2$cq18b)[3]
                        "
```
Any idea?

Thank you for your time and attention,
Ángel

**Comment by angelrodriguez2020** [comment]
Dear Stef,

Thank you for your help.

Your 'post' solution works for numeric variables to predict aid, but not for factors. Please see what happens when I introduce a factor as a predictor in your code:

`data <- data.frame(
  age = c(60, 54, 82, NA, 34, 58, 60, 58, 76, 40),
  fall = c(0, NA, 1, 0, 1, NA, 1, 1, 0, 1),
  aid = factor(c("-", NA, "Yes", "-", "No", NA, "Yes", NA, NA, "No")),
  sex = factor(c("M", NA, "F", "F", "M", NA, "M", "F", "F", "M"))
)

pred <- make.predictorMatrix(data)
pred["fall", "aid"] <- 0
pred["age", "aid"] <- 0
pred["sex", "aid"] <- 0

post <- make.post(data)
post["aid"] <- paste(sep = "; ",
                     "fall <- data$fall[!r[,j]] == 1",
                     "idx <- data$fall == 1",
                     "imp[[j]][!fall, i] <- levels(data$aid)[1]",
                     "imp[[j]][fall, i] <- mice.impute.pmm(y = data$aid[idx], ry = r[idx, j], 
                     x = model.matrix(aid ~ 0 + age + sex , data[idx, , drop = FALSE]))")
                     
imp <- mice(data, m = 10, pred = pred, post = post, seed = 1)`

>imp <- mice(data, m = 10, pred = pred, post = post, seed = 1)

 iter imp variable
  1   1  age  fall  aid
 Error in get("printFlag", parent.frame(search.parents("printFlag"))) : 
  object 'printFlag' not found

**Comment by stefvanbuuren** [comment]
The devil is in the details. Nothing is wrong with your code. 

Apparently, the introduction of `mice.impute.pmm()` at this - somewhat unusual - point in the algorithm surprised the function that finds the printing flag. We'll correct that.

**Comment by stefvanbuuren** [comment]
Solved in `mice 3.11.2`

**Comment by angelrodriguez2020** [comment]
Dear Stef,
Thank you.
I can update to mice 3.11.0, not to mice 3.11.2. 
When would that be possible?
Ángel

**Comment by stefvanbuuren** [comment]
See <https://github.com/amices/mice>

**Comment by angelrodriguez2020** [comment]
Thank you Stef, but I couldn´t. This is what I got (R 4.0.2, Windows 10):

> devtools::install_github(repo = "amices/mice")
Downloading GitHub repo amices/mice@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                              
2: CRAN packages only               
3: None                             
4: vctrs     (0.3.3 -> 0.3.4) [CRAN]
5: backports (1.1.7 -> 1.1.9) [CRAN]

Enter one or more numbers, or an empty line to skip updates:1
vctrs     (0.3.3 -> 0.3.4) [CRAN]
backports (1.1.7 -> 1.1.9) [CRAN]
Installing 2 packages: vctrs, backports
Installing packages into ‘C:/Users/arodr/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)

  There are binary versions available but the source versions are later:
          binary source needs_compilation
vctrs      0.3.3  0.3.4              TRUE
backports  1.1.7  1.1.9              TRUE

installing the source packages ‘vctrs’, ‘backports’

trying URL 'https://ftp.cixug.es/CRAN/src/contrib/vctrs_0.3.4.tar.gz'
Content type 'application/x-gzip' length 995078 bytes (971 KB)
downloaded 971 KB

trying URL 'https://ftp.cixug.es/CRAN/src/contrib/backports_1.1.9.tar.gz'
Content type 'application/x-gzip' length 18903 bytes (18 KB)
downloaded 18 KB

* installing *source* package 'vctrs' ...
** package 'vctrs' successfully unpacked and MD5 sums checked
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/Users/arodr/Documents/R/win-library/4.0/vctrs'
* restoring previous 'C:/Users/arodr/Documents/R/win-library/4.0/vctrs'
Error in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) : 
  (converted from warning) problem copying C:\Users\arodr\Documents\R\win-library\4.0\00LOCK-vctrs\vctrs\libs\x64\vctrs.dll to C:\Users\arodr\Documents\R\win-library\4.0\vctrs\libs\x64\vctrs.dll: Permission denied
* removing 'C:/Users/arodr/Documents/R/win-library/4.0/vctrs'
* restoring previous 'C:/Users/arodr/Documents/R/win-library/4.0/vctrs'
Error in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) : 
  (converted from warning) problem copying C:\Users\arodr\Documents\R\win-library\4.0\00LOCK-vctrs\vctrs\libs\x64\vctrs.dll to C:\Users\arodr\Documents\R\win-library\4.0\vctrs\libs\x64\vctrs.dll: Permission denied
Execution halted
Error: Failed to install 'mice' from GitHub:
  (converted from warning) installation of package ‘vctrs’ had non-zero exit status
>

**Comment by stefvanbuuren** [comment]
Not related to `mice`, so please look elsewhere to solve this.

**Comment by LaurenceGeebelen** [comment]
Dear all,

I'm trying to solve a similar problem, however in my example aid would have an additional level, leaving 3 options when fall == 1  and I would like to use "polyreg" as a method for the imputation (as this is used for other multicategorical variables in my imputation model), I keep getting errors when adapting following code to polyreg , can someone help?  

post["aid"] <- paste(sep = "; ",
                     "fall <- data$fall[!r[,j]] == 1",
                     "idx <- data$fall == 1",
                     "imp[[j]][!fall, i] <- levels(data$aid)[1]",
                     "imp[[j]][fall, i] <- mice.impute.pmm(**y = data$aid[idx], ry = r[idx, j], x = model.matrix(aid ~ 0 + age, data[idx, , drop = FALSE]))**")

Thank you!
Laurence
