### ISSUE TITLE
Data contains NAs after imputation, no evidence for constant values or collinearity

### ISSUE THREAD

**Issue by Michael-Covell** [amices/mice#263]
I have NAs after I run mice() when I "skip" imputation of some variables using this line of code...
`meth[c('revenue','units','category','menu','menu_agg')] <- ""`

There is no warning message about constant values and the correlation matrix (among numeric variables) looks like this...
```
dfr <- df[,c('broilers_boosted','revenue','units')]
cor(dfr, use = "pair")

| broilers_boosted | revenue | units
1.0000000 | 0.5961082 | 0.6432247
0.5961082 | 1.0000000 | 0.6547681
0.6432247 | 0.6547681 | 1.0000000
```

I am interested only in imputing values for broilers_boosted.  Here is the full code I am running:
[Example.txt](https://github.com/amices/mice/files/5138471/Example.txt)
```
df <- read.csv("df.txt)"
ini <- mice(df, maxit = 0)
pred = ini$predictorMatrix
pred[c("revenue",'units', 'category', 'menu', 'menu_agg'),] <- 0
pred[,c('category', 'menu', 'menu_agg')] <- 0
meth <- ini$meth
meth["broilers_boosted"] <- "norm"
meth[c('revenue','units','category','menu','menu_agg')] <- "" #only part of the data is imputed when I include this line
xyz <- mice(df, predictorMatrix=pred, method=meth)
colSums(is.na(complete(xyz)))
```

Again, I am interested only in imputing values for broilers_boosted, but if (and only if) I skip imputation of the other variables, mice() only partially imputes data for broilers_boosted such that there are still NAs after imputation.  Is this a bug?

**Comment by stefvanbuuren** [comment]
This is normal behaviour. The line 
```r
meth[c('revenue','units','category','menu','menu_agg')] <- ""
```
instruct `mice` to skip imputation for some variables, but these later are needed to impute `broilers_boosted`. Hence if they contain missing values in some rows, then `mice` cannot calculate imputations for these rows, and `NA`s will result. 

You would need to remove the predictors from the imputation model for `broilers_boosted` if you do not want this from happening, e.g. by setting
```r
pred["broilers_boosted", c("revenue",'units', 'category', 'menu', 'menu_agg')] <- 0
```
