### ISSUE TITLE
Passive imputation of a "grouped by" variable

### ISSUE THREAD

**Issue by markseeto** [amices/mice#277]
Thanks for providing the mice package.

Is it possible to do passive imputation of a variable that is not a simple transformation of other variables?

For example, suppose we have this data:
```
d <- data.frame(subject = rep(LETTERS[1:5], each = 3),
                x = rep(c(6.5, 4.4, 1.3, NA, 4.3), each = 3),
                age = c(20.2, 24.3, 30.9,
                        23.1, 26.4, 31.4,
                        19.2, 24.1, 28.2,
                        18.8, 25.1, 27.9,
                        24.2, 26.5, 31.5),
                y = c(10.2, 15.6, 18.7,
                      NA, 15.6, 18.9,
                      6.2, NA, 17.6,
                      18.1, 18.8, 19.9,
                      NA, 15.2, 19.1),
                y0 = rep(c(10.2, NA, 6.2, 18.1, NA), each = 3))

d

##    subject   x  age    y   y0
## 1        A 6.5 20.2 10.2 10.2
## 2        A 6.5 24.3 15.6 10.2
## 3        A 6.5 30.9 18.7 10.2
## 4        B 4.4 23.1   NA   NA
## 5        B 4.4 26.4 15.6   NA
## 6        B 4.4 31.4 18.9   NA
## 7        C 1.3 19.2  6.2  6.2
## 8        C 1.3 24.1   NA  6.2
## 9        C 1.3 28.2 17.6  6.2
## 10       D  NA 18.8 18.1 18.1
## 11       D  NA 25.1 18.8 18.1
## 12       D  NA 27.9 19.9 18.1
## 13       E 4.3 24.2   NA   NA
## 14       E 4.3 26.5 15.2   NA
## 15       E 4.3 31.5 19.1   NA
```
The variable `y0` is the value of `y` for the youngest `age`, for each subject. We might want to allow the slope of `y` vs `age` to depend on `y0`.

Using mice, is it possible to passively impute `y0`?

**Comment by stefvanbuuren** [comment]
It seems that you want imputed values of `y0` to be identical within the groups defined by `subject`. Correct?

See <https://stefvanbuuren.name/fimd/sec-level2pred.html>  for techniques to solve that problem.

**Comment by markseeto** [comment]
Thanks for your reply Stef.

Yes it's correct that `y0` should be identical within each subject. But `y0` is deterministically related to `subject`, `age` and `y` (`y0` is the value of `y` corresponding to the lowest `age` for each `subject`), which is why I thought it might be possible to use passive imputation for `y0`. I don't see how the `2l` functions would be used to do that.

**Comment by stefvanbuuren** [comment]
Ah, I missed that. There is no standard solution for that in `mice`, but you could probably adapt `mice.impute.2lonly.mean()` to return the value of the first record in the class.

**Comment by markseeto** [comment]
Thanks Stef.
