### ISSUE TITLE
mice.impute.rf currently uses means not nodes

### ISSUE THREAD

**Issue by prockenschaub** [amices/mice#288]
### Problem description

The current implementation of `mice.impute.rf` seems to attempt to find donors based on the node to which an observation with missing data was assigned.

https://github.com/amices/mice/blob/160b02ebcac87c1e992d51055910d710e53a8d79/R/mice.impute.rf.R#L61

However, `randomForest` returns nodes only as an attribute of the prediction object and `yobs[leafnr == s]` therefore matches based on predictions (and not on nodes). This gives the same result if all nodes give unique predictions, but may differ if two nodes happen to have the same prediction. 

### Reproducible example

``` r
library(mice)
library(randomForest)

ry <- !is.na(nhanes$bmi)
wy <- !ry
xobs <- nhanes[ry, "age", drop = FALSE]
xmis <- nhanes[wy, "age", drop = FALSE]
yobs <- nhanes[ry, "bmi"]

fit <- randomForest::randomForest(x = xobs, y = yobs, ntree = 1)

# Current implementation: nodes are an attribute, 
#                         comparison is based on predicted BMI
predict(object = fit, newdata = xobs, nodes = TRUE)
#>        2        5        7        8        9       13       14       15 
#> 23.50000 26.86667 26.86667 26.86667 23.50000 24.13750 23.50000 26.86667 
#>       17       18       19       20       22       23       24       25 
#> 24.13750 23.50000 26.86667 24.13750 26.86667 26.86667 24.13750 23.50000 
#> attr(,"nodes")
#>    1
#> 2  4
#> 5  2
#> 7  2
#> 8  2
#> 9  4
#> 13 5
#> 14 4
#> 15 2
#> 17 5
#> 18 4
#> 19 2
#> 20 5
#> 22 2
#> 23 2
#> 24 5
#> 25 4

# Updated: comparison is made based on nodes. This can lead
#          to the same result (if all nodes have unique predictions)
#          or to different results (if some nodes share the same)
#          prediction
as.vector(attr(predict(object = fit, newdata = xobs, nodes = TRUE), "nodes"))
#>  [1] 4 2 2 2 4 5 4 2 5 4 2 5 2 2 5 4
```

**Comment by stefvanbuuren** [comment]
Thanks for finding and correcting this glitch. The idea of `rf` is indeed to sample only from the leaf where the incomplete target case ends up.

I expect that in practice the effect of the glitch will be minor. Agree?

**Comment by prockenschaub** [comment]
Agreed, this should ever only matter if there are two nodes with the same mean, and even then one might argue that since they have the same mean they are likely to be similar.
