### ISSUE TITLE
pool error

### ISSUE THREAD

**Issue by benjaminwnelson** [amices/mice#294]
When I run summary(mice::pool.fitlist(model)) it gives this error. Any on how to address this would be appreciated!

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'summary': No tidy method for objects of class qr
In addition: Warning messages:
1: In get.dfcom(object, dfcom) : Infinite sample size assumed.
2: 'tidy.numeric' is deprecated.
See help("Deprecated")

**Comment by stefvanbuuren** [comment]
Please search the closed issues before opening a new one.

**Comment by benjaminwnelson** [comment]
Hello, thank you for your response. Unfortunately, I looked through the closed issues and I am still getting the error after using broom and pool.scalar. Please let me know if you would be able to point me towards a way to deal with this issue.

**Comment by benjaminwnelson** [comment]
Hi @stefvanbuuren, I have continued to try to troubleshoot this issue and still have the same issue. Please let me know if you would be able to point me towards a way to deal with this issue.

**Comment by stefvanbuuren** [comment]
Related: #106, #123, #217
