### ISSUE TITLE
Using imputation models already fitted to impute missing values in new individuals?

### ISSUE THREAD

**Issue by eusebe** [amices/mice#299]
Hi, 

I was wondering if it is possible (and if yes, how) to implement one of the methods described in https://onlinelibrary.wiley.com/doi/10.1002/sim.8682 (open access) for the imputation of missing predictor values in *new* individuals with missing data. More precisely, I would like to implement the method 6, which use the vector of parameter estimates for each of the fully conditional models as derived in a development dataset (where missing values were imputed by MICE) to impute missing data in new individuals. The method is described in the last paragraph of section 2.3.
I guess this is not straightforward, but is it possible using the mice package?

Best, 
David

**Comment by stefvanbuuren** [comment]
There was an old request for this feature at #32. See the discussion - and our solution using the `ignore` argument - to split the data into a train set (on which we fit the imputation model) and a test set (on which we apply the imputation model). Would that be useful for your case?

**Comment by eusebe** [comment]
I'm going to dive in, thanks!
