### ISSUE TITLE
Issue with Stepwise Model Selection after imputation

### ISSUE THREAD

**Issue by SunshineCheesesauce** [amices/mice#300]
Hello,
I have been following your Stepwise Model Selection as per 5.4 of Flexible Imputation of Missing Data.
It has been working fine for me and have had great results.
However, after a recent R update, it no longer works.
I tried with my own data and then the code exactly as in the workbook:
data <- boys[boys$age >= 8, -4]
imp <- mice(data, seed = 28382, m = 10, print = FALSE)
scope <- list(upper = ~ age + hgt + wgt + hc + gen + phb + reg,
              lower = ~1)
expr <- expression(f1 <- lm(tv ~ 1),
                   f2 <- step(f1, scope = scope))
fit <- with(imp, expr)

This is all fine but when I get to this section:
formulas <- lapply(fit$analyses, formula)
An error is thrown that says:
Error in formula.default(X[[i]], ...) : invalid formula

Can you help me with any ideas as to what is going wrong here?

Using R-4.0.3, mice 3.12.0

Thanks!

**Comment by stefvanbuuren** [comment]
It appeared that my changes in the `with()` function in `mice 3.12.0` broke some old code. I have restored the old `with()` in <https://github.com/amices/mice/commit/b2f7ec5db5b3c88c74f33c000443e80784054f79>. Could you retry your example using the development version `devtools::install_github(repo = "amices/mice")`?

**Comment by SunshineCheesesauce** [comment]
Thank you so much. That has fixed it
