### ISSUE TITLE
installation problem Mac

### ISSUE THREAD

**Issue by EileenRoe** [amices/mice#307]
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/mice_3.13.0.tgz': HTTP status was '404 Not Found'

Any ideas how to solve this problem?
Thank you

**Comment by maureenkelly03** [comment]
I'm having the same issue.

**Comment by gerkovink** [comment]
Can reproduce. 

Use `install.packages("mice", type = "source")` to install from source. This avoids the non-existent pre-compiled binary. 

All the best, 

Gerko

**Comment by gerkovink** [comment]
Reason for the error is: the pre-compiled version of the `mice` package is still at `mice_3.12.0.tgz`, while the source version is already at `mice_3.13.0`.
