### ISSUE TITLE
Use robust.se when pooling coxph models

### ISSUE THREAD

**Issue by ngreifer** [amices/mice#310]
When pooling `survival::coxph()` models across imputations, the "naive" standard error is used even when `robust = TRUE` is specified in the `coxph()` call within `with()` (which requests robust standard errors). This is because `tidy()` stores the robust standard error in the `robust.se` column rather than the `std.error` column, the latter of which is used when computing `ubar` in `pool.fitlist()`. Could you add a check to see if a robust standard error is requested and then use that instead of the naive standard error? This could be done by adding to `pool.fitlist()` the following:
```
if ("robust.se" %in% names(w)) w$std.error <- w$robust.se
```
Thank you!

**Comment by stefvanbuuren** [comment]
Since `robust = TRUE` is a setting of `coxph()` it seems more natural to ask for this functionality in `tidy()`  So, if the user requests `robust = TRUE`, I would expect that `tidy()` would set `w$std.error` to be the robust version.

**Comment by ngreifer** [comment]
I agree. I was hesitant to ask the `broom` authors for this because it could affect some reverse dependencies. I think the motivation behind the `tidy()` approach is that `std.error` always contains the conventional standard errors, and `robust.se` is an extra column added only when requested. This isn't how it's done in `coxph()` itself, though; the `var` component of the output is the conventional SE when `robust = FALSE` and the robust SE when `robust = TRUE`, with the conventional SE stored in `naive.se`. So the `var` component in `coxph` objects always contains the requested SE, whereas the `std.error` column in `tidy()` output always contains the conventional standard error, regardless of whether the robust SE was also requested.

I don't think they will want to change this because the `std.error` has always meant one thing for `coxph` objects and they may not want it to suddenly mean something different, whereas right now `mice` essentially ignores the robust SE because it's not in the usual place `pool.fitlist()` looks for SEs. My request is that `mice` broaden its search for the desired SE beyond just the `std.error` column. This might be more appealing than the `broom` authors changing the meaning of the `std.error` column.

There is already a precedent in `mice` of treating `coxph` objects differently (e.g., in `get.dfcom()`), and my request would be as simple as adding the following line to `pool.fitlist()`:
```
if ("robust.se" %in% names(w)) w$std.error <- w$robust.se
```
I suppose that does make the assumption that the robust SE is always desired when available (though my understanding is that `coxph` and `aareg` objects are the only ones that get this column from `tidy()`).

**Comment by stefvanbuuren** [comment]
OK, thanks for explaining. 

I just pushed `mice 3.13.2`, which updates the `pool()` function.
