### ISSUE TITLE
How to solve error: Error in solve.default(xtx + diag(pen)) : system is computationally singular: reciprocal condition number =2.06642e-16?

### ISSUE THREAD

**Issue by lg401981952** [amices/mice#320]
method = 'pmm', data size is 6000*750 , All variables are numeric 

> imp <- mice(data,m=5,seed = 1)

Then, I get a error.

> Error in solve.default(xtx + diag(pen)) : system is computationally singular: reciprocal condition number =2.06642e-1

 I want to know  what causes this error (muticollinearity?), and how to solve it?

Thanks!

**Comment by stefvanbuuren** [comment]
Take a look at <https://stefvanbuuren.name/fimd/sec-toomany.html#finding-problems-loggedevents>. 

If you're only interested in getting the software to run, try a quick-and-dirty solution like `pred <- quickpred(data); mice(data, pred = pred)`.

**Comment by lg401981952** [comment]
Thanks for your quick reply. It's very useful
