### ISSUE TITLE
Error from mice.impute.2l.lmer() when specifying fixed effects only

### ISSUE THREAD

**Issue by cshawsome** [amices/mice#384]
I'm having trouble imputing with 2l.lmer() when I only include fixed effects in the predictor matrix. I specify ID as the clustering variable by using -2 and specify the other 23 variables as fixed effects by using 1 in the predictor matrix. When I run the function I get this error message: `Error in Xi %*% beta.star : non-conformable arguments`

I thought this might be related to a previously closed issue about 2l.norm() where the solution at that time was to include every predictor as a random effect: https://github.com/amices/mice/issues/62

When I specify all predictors as random effects in 2l.lmer(), the function runs but my diagnostic plots are completely flat. 

<img width="564" alt="Screen Shot 2021-04-13 at 10 20 46 AM" src="https://user-images.githubusercontent.com/35509577/114598637-fb23c000-9c46-11eb-8ac0-2ee6399a3b69.png">

Using 2l.norm() with fixed effects only with the same dataset runs and produces chains that mix, though. Is there something I'm missing about the 2l.lmer() function?

**Comment by stefvanbuuren** [comment]
Hmm, that doesn't look OK. 

Could you make a small reprex that shows the problem?

**Comment by cshawsome** [comment]
Thank you for this quick response! I've created a synthetic dataset [data_long.csv](https://github.com/amices/mice/files/6313026/data_long.csv) that can be plugged into the following code:

```
#---- read in data ----
data_long <- read_csv(here::here("data", "data_long.csv"))
time_updated_vars <- c("Ci", "age")
time_invariant_vars <- c("female")

#---- predictor matrix ----
blocks <- time_updated_vars
predict <- matrix(1, length(blocks), ncol = ncol(data_long)) %>% 
  set_rownames(blocks) %>% 
  set_colnames(colnames(data_long))

#Don't use these as predictors
predict[, c("wave")] <- 0

#Indicated cluster variable
predict[, "id"] <- -2

#Can't predict themselves
predict[time_updated_vars, time_updated_vars] <- 
  (diag(x = 1, nrow = length(time_updated_vars), 
        ncol = length(time_updated_vars)) == 0)*1

#---- impute ----
data_imputed <- mice(data = data_long, 
                     m = 2, maxit = 5, method = "2l.lmer", 
                     predictorMatrix = predict, where = is.na(data_long), 
                     blocks = as.list(rownames(predict)), 
                     seed = 20210126)
```
I checked and get the same behavior: Error for specifying everything as a fixed effect, Flat diagnostics when everything is a random effect. Please let me know if you have any trouble with the data file.

**Comment by stefvanbuuren** [comment]
Thanks. I could reproduce and found the problem.

Cluster 14 in your data contains just one observation, which confused `as.matrix()` so that it returned a matrix of the wrong shape. I have now deleted `as.matrix()` in line 142 of `mice.impute.2l.lmer()`, and now your code runs.

`mice 3.13.6` incorporates the fix. Could you check on your real data?

**Comment by stefvanbuuren** [comment]
@shahabjolani Could you perhaps take a look at the flat lines plots, which look interesting/curious?

**Comment by shahabjolani** [comment]
@stefvanbuuren @cshawsome I'll take a closer look at the flat lines this weekend...

**Comment by stefvanbuuren** [comment]
OK, thanks. 

I understand that the cause of the flat lines is that `mice.impute.2l.lmer()` returns the current imputations, and bypasses the update. I think we can leave it like that (what else to do?), but document the behaviour. The flat lines as well as the warning itself should then alert the user.

I'll open a new issue for this.

**Comment by shahabjolani** [comment]
Indeed, the flat lines can act as an alert. However, this is not necessarily the behaviour of mice.impute.2l.lmer(), I think. If an imputation function (like this one) does not run, you will get such flat lines anyway...

**Comment by cshawsome** [comment]
> Thanks. I could reproduce and found the problem.
> 
> Cluster 14 in your data contains just one observation, which confused `as.matrix()` so that it returned a matrix of the wrong shape. I have now deleted `as.matrix()` in line 142 of `mice.impute.2l.lmer()`, and now your code runs.
> 
> `mice 3.13.6` incorporates the fix. Could you check on your real data?

checked the fix on my real data and it works-- thank you!
