### ISSUE TITLE
Document flat-line behaviour of mice.impute.2l.lmer() 

### ISSUE THREAD

**Issue by stefvanbuuren** [amices/mice#385]
Issue #384 identifies that trace plots become flat if there is a problem with fitting the `lme4::lmer()` model. It issues a warning and return the old imputations, leading the flat trace lines. 

This behaviour needs to be documented.

**Comment by shahabjolani** [comment]
Indeed, the flat lines can act as an alert. However, this is not necessarily the behaviour of mice.impute.2l.lmer(), I think. If an imputation function (like this one) does not run, you will get such flat lines anyway...

**Comment by stefvanbuuren** [comment]
Imputation methods may use several strategies to deal with running errors. I might be that `mice.impute.2l.lmer()` is unique in returning the old imputes. 

`mice 3.13.7` adds to the docs:

```
If lme4::lmer() fails, the procedure prints the warning "lmer does not run. Simplify imputation model" 
and returns the current imputation.  If that happens we see flat lines in the trace line plots. 
Thus, the appearance of flat trace lines should be taken as an additional alert to a problem with 
imputation model fitting.
```
