### ISSUE TITLE
Revisions to documentation of `post` and `loggedEvents`

### ISSUE THREAD

**Issue by bgall** [amices/mice#386]
I've found two areas where additions to the package documentation and/or vignettes would prove beneficial:

## loggedEvents

`loggedEvents` is described in the mids object description on page 129 of the [documentation.](https://cran.r-project.org/web/packages/mice/mice.pdf) The documentation states that the last column (`out`) of the loggedEvents data frame is "a (possibly long) character vector with the names of the altered or removed predictors."

This description would benefit from more specificity regarding how to interpret the values of `out` when `mice()` internally handles categorical predictors or the user specifies non-parametric methods (e.g. `method = "rf"`) are used. In cases where the user does not specify a specific parametric model formula with numeric predictors, it can be unclear how to interpret the events. For example, the events log in the below produces values of `out` that include w^4, w.L, w.Q, zh, yb, w.C, but it is not clear where the polynomials originate or what ".L", ".C", or "yb" convey. 

```
set.seed(123)

### Sample data
dat <- data.frame(w = ordered(as.factor(sample(c(1:5,NA),20, replace = T))),
                  x = c(1:10,rep(NA_real_,10)),
           y = sample(c(NA_character_,"a","b"),20, replace = TRUE),
           z = as.factor(sample(c(NA_character_,"g","h"),20, replace = TRUE))
)

### Impute 2 datasets
imputed <- mice::mice(dat, m = 2,  
                      maxit = 10, seed = 123)

### Check logged events
imputed$loggedEvents
```

## post

The documentation uses different language at times which can make it confusing as to whether `post` processes imputed values after each iteration or after all iterations are completed. The `post` argument is described in the description of `mice()` (p.74):

> "A vector of strings with length ncol(data) specifying expressions as strings.
> Each string is parsed and executed within the sampler() function to post-process
> imputed values during the iterations.

Meanwhile it is described in `make.post` (p.63) via:

> The post vector is an argument to the mice
> function that specifies post-processing for a variable just after imputation

I recall this being ambiguous in some of the vignettes as well.

**Comment by stefvanbuuren** [comment]
Thanks for your suggestions, which all make sense. 

I will look into it. I'd be also happy to accept a pull request that straightens these hiccups.

**Comment by bgall** [comment]
Submitted a pull request with changes to the `make.post` documentation. I couldn't do so for the other point as I am not actually sure what `loggedEvents["out"]`  is communicating in cases such as the minimal example I provided. I didn't see anything in the univariate imputation method or `make()` code that determines those values, so not even sure what is producing those values.

**Comment by stefvanbuuren** [comment]
Now part of `mice 3.13.12`. Thanks for the contribution.
