### ISSUE TITLE
Performance issues in combination with OpenBLAS

### ISSUE THREAD

**Issue by gowerc** [amices/mice#395]
I'm not exactly sure whats going on here but will try to describe the issue as best I can.  

We work in docker containers that share a central resource from a kubernetes pod.  The reason I mention this is is that our containers are set CPU restrictions of 16  I.e. if we try to run a multiple-process or multiple-threaded programs that uses more than 16 cpus at a time our resource usage gets throttled. 

It's here that I notice a bizarre interaction between mice and BLAS (we use OpenBLAS in particular). 

mice seems to use BLAS and spawns multiple threads in accordance to the thread limit, however changing the number of threads to be between 1-16 doesn't change mice's performance at all (as in I get the same performance speed regardless of how many threads I select).  However if I increase the number of threads over 16 then it triggers the CPU throttling so its clearly using resource somewhere....

Is this behaviour expected ? My assumption would have been to see a performance improvement by increasing the number of BLAS threads until hitting the throttling limit. 

Code example:
```
library(mice)
library(dplyr)
library(purrr)
library(RhpcBLASctl)


### Create a dataset for mice to impute
set.seed(102)
n <- 7500
dat_mice <- tibble(result = rbinom(n, 1, 0.8))
for(i in 1:15) dat_mice[paste0("v",i)] <- rnorm(n)
dat_mice_amp <- mice::ampute(dat_mice)$amp


runme <- function(n_threads){
    blas_set_num_threads(n_threads)
    set.seed(404)
    start <- Sys.time()
    x <- capture.output({mice(dat_mice_amp)})
    stop <- Sys.time()
    res <- as.numeric(difftime(stop,start, units = "secs"))
    return(res)
}

results <- tibble(n_threads = c(1,2,4,8,16,32,64)) %>% 
    mutate(time = map_dbl(n_threads, runme))
```

Outcome:
```
# A tibble: 7 x 2
  n_threads  time
      <dbl> <dbl>
1         1  6.07
2         2  6.23
3         4  6.47
4         8  6.58
5        16  6.55
6        32 18.4 
7        64 39.4 
```

**Comment by gerkovink** [comment]
You create continues data, which would use "mice.impute.pmm" as its imputation method. The estimation in here is done with `estimice()`, which by default uses QR decomposition and the matching is done in c. I don't see where the added benefit of using BLAS would be.

**Comment by gowerc** [comment]
Hey @gerkovink , 

Sorry to be clear I'm not advocating for using BLAS I am pointing out that there seems to be some interaction between mice and BLAS.  As in it appears mice is spawning BLAS threads which in turn is tripping up and activating the docker cpu throttling. 

My confusion is why these BLAS threads are being spawned if they are not being used to speed up the computation. 

This was noticed by a colleague who tried to use parlmice but ended up having slower run times as it spawns X BLAS threads per process (where x = the limit set by `OPENBLAS_NUM_THREADS`) .  We have a solution in that we can use `RhpcBLASctl ::blas_set_num_threads(1)` to stop excessive number of BLAS threads being created  but alas my confusion is to why mice is spawning them in the first place if they aren't being used.

**Comment by gerkovink** [comment]
Like I said, QR decomposition may benefit from BLAS. This step is done in every substep of every iteration. So, for a fully defined predictor matrix on 100 incomplete columns with 10 iterations, the call will be executed 100x10=1000 times. This should not be a computationally nor time-intensive step, though. Your first 16 threads confirm this. The additional performance drop when increasing the threads is unclear to me, as it could stem from a plethora of machine, session and memory interactions. 

Perhaps @stefvanbuuren has a better insight whether the described behaviour would fall outside our expectations. 

I will run some test later today when I have time to look at this

**Comment by gowerc** [comment]
O Apologies I miss-understood you. 

I have raised a query with our IT group to get a better understanding of how the docker cpu limitation operates but I think our containers are restricted via the `--cpu` [argument](https://docs.docker.com/config/containers/resource_constraints/#cpu) .  Its not clear to me though what this does under the hood though. 

As a pure speculation I am wondering if those initial calls to BLAS for the QR decomposition are enough to trigger the throttling even though there is no pro-longed intensity :S  i.e. it sees a instance of calling to more cpus than allowed and essentially overreacts ? Again just a guess though :(

**Comment by gerkovink** [comment]
I cannot reproduce your findings on my machine

``` r
library(mice)
library(dplyr)
library(tibble)
library(purrr)
library(RhpcBLASctl)


### Create a dataset for mice to impute
set.seed(102)
n <- 7500
dat_mice <- tibble(result = rbinom(n, 1, 0.8))
for(i in 1:15) dat_mice[paste0("v",i)] <- rnorm(n)
dat_mice_amp <- mice::ampute(dat_mice)$amp


runme <- function(n_threads){
  blas_set_num_threads(n_threads)
  set.seed(404)
  start <- Sys.time()
  x <- capture.output({mice(dat_mice_amp)})
  stop <- Sys.time()
  res <- as.numeric(difftime(stop,start, units = "secs"))
  return(res)
}

tibble(n_threads = c(1,2,4,8,16,32,64)) %>% 
  mutate(time = map_dbl(n_threads, runme))
#> # A tibble: 7 x 2
#>   n_threads  time
#>       <dbl> <dbl>
#> 1         1  10.8
#> 2         2  10.7
#> 3         4  11.1
#> 4         8  10.7
#> 5        16  10.4
#> 6        32  10.5
#> 7        64  10.5
```

<sup>Created on 2021-05-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by gerkovink** [comment]
FWIW

``` r
sessionInfo()
#> R version 4.0.5 (2021-03-31)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Catalina 10.15.7
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] RhpcBLASctl_0.20-137 purrr_0.3.4          tibble_3.1.1        
#> [4] dplyr_1.0.5          mice_3.13.0         
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.6        pillar_1.6.0      compiler_4.0.5    highr_0.9        
#>  [5] tools_4.0.5       digest_0.6.27     evaluate_0.14     lifecycle_1.0.0  
#>  [9] lattice_0.20-41   pkgconfig_2.0.3   rlang_0.4.10      reprex_2.0.0     
#> [13] DBI_1.1.1         yaml_2.2.1        xfun_0.22         withr_2.4.2      
#> [17] styler_1.4.1      stringr_1.4.0     knitr_1.33        generics_0.1.0   
#> [21] fs_1.5.0          vctrs_0.3.7       grid_4.0.5        tidyselect_1.1.0 
#> [25] glue_1.4.2        R6_2.5.0          fansi_0.4.2       rmarkdown_2.7    
#> [29] tidyr_1.1.3       magrittr_2.0.1    backports_1.2.1   ellipsis_0.3.1   
#> [33] htmltools_0.5.1.1 assertthat_0.2.1  utf8_1.2.1        stringi_1.5.3    
#> [37] broom_0.7.6       crayon_1.4.1
```

<sup>Created on 2021-05-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by gerkovink** [comment]
> I have raised a query with our IT group to get a better understanding of how the docker cpu limitation operates but I think our containers are restricted via the `--cpu` [argument](https://docs.docker.com/config/containers/resource_constraints/#cpu) . Its not clear to me though what this does under the hood though.

This would explain your findings.

**Comment by gowerc** [comment]
I was able to replicate the issue using the public rocker docker images on my mac-book (using a limit of 2 for brevity):

```
docker run -it --rm --cpus=2 rocker/r-ver:4.0.4 R
```

```
install.packages(c("mice","dplyr", "purrr", "RhpcBLASctl"))
library(mice)
library(dplyr)
library(purrr)
library(RhpcBLASctl)


### Create a dataset for mice to impute
set.seed(102)
n <- 7500
dat_mice <- tibble(result = rbinom(n, 1, 0.8))
for(i in 1:15) dat_mice[paste0("v",i)] <- rnorm(n)
dat_mice_amp <- mice::ampute(dat_mice)$amp


runme <- function(n_threads){
    blas_set_num_threads(n_threads)
    set.seed(404)
    start <- Sys.time()
    x <- capture.output({mice(dat_mice_amp)})
    stop <- Sys.time()
    res <- as.numeric(difftime(stop,start, units = "secs"))
    return(res)
}

results <- tibble(n_threads = c(1,2,4,8)) %>% 
    mutate(time = map_dbl(n_threads, runme))
results
```


```
# A tibble: 4 x 2
  n_threads  time
      <dbl> <dbl>
1         1  5.66
2         2  5.19
3         4 12.1
4         8 24.6
```

**Comment by gowerc** [comment]
I appreciate this isn't strictly a mice issue but more of an interaction between mice/blas and docker.  I guess my concern is that less technical users get stung by these interactions as they are unaware of thats going on behind the scenes (particularly in the case of parlmice).  Considering that mice doesn't really get any meaningful performance increase from blas is it possible / feasible for mice to be hard coded to just use 1 thread (with an option to use more?) to avoid users tripping themselves up in these environments ?

**Comment by gerkovink** [comment]
This would indeed mean that your findings stem from the docker specification, and not from `mice`. I am not sure that limiting `mice` by default to scenarios that users might induce would be a proper way of going about this behaviour.

**Comment by gowerc** [comment]
In general I would tend to agree with you, my only thought is that setting such a limit doesn't seem to impact mice in any meaningful way. As in by your own tests it seemed to make 0 difference:

```
#> # A tibble: 7 x 2
#>   n_threads  time
#>       <dbl> <dbl>
#> 1         1  10.8
#> 2         2  10.7
#> 3         4  11.1
#> 4         8  10.7
#> 5        16  10.4
#> 6        32  10.5
#> 7        64  10.5
```

So I guess I would hope that such a change provides benefits to mice users who are using it in these niche environments whilst not having any impact on the wider user base ?

**Comment by gerkovink** [comment]
I agree with your rationale, but wouldn't a proactive restriction not negatively impact the performance of those docker instances that are not bound by limiting parameters?

**Comment by stefvanbuuren** [comment]
In general I would not like to restrict `mice` to a specific external environment, but if `mice` creates problem, then we should think about a fix.
- Are we already clear that it is `mice::estimate()` that causes the BLAS threads?
- Would it be possible to prevent spawning by passing a NO-BLAS flag to `estimice()`?

**Comment by gowerc** [comment]
O, apologies,  indeed I agree mice should not alter the overall environment, I was just wondering if it was possible for mice to call and use blas with only 1 thread regardless of what the system wide defaults were ? 

Sorry I  have no knowledge of C or the underlying libraries but I was working on the assumption that when you invoke BLAS that you would be able to provide an argument / configuration variable just for your invokation.

**Comment by gerkovink** [comment]
`mice` does not directly invoke BLAS. I think the result is stemming from a lower level routine invocation, such as e.g LAPACK or similar by nested R-core functions such as `chol()`, `lm()`, `solve()`, etc.

**Comment by gowerc** [comment]
Ah yes indeed in that case I see how it is much more problematic to request you guys to change this in mice, I made the assumption that you called out to BLAS directly with your C code.

Yes re-running using `method = "sample"` appears to have the same issue:

```
# A tibble: 4 x 2
  n_threads  time
      <dbl> <dbl>
1         1  3.97
2         2  3.77
3         4  6.13
4         8  8.97
```

**Comment by gerkovink** [comment]
Thanks a lot from confirming! Since the core of `mice` is sampling, I fear we cannot solve this from within. The conclusion is that this behaviour is expected.

Thanks from raising this issue. I'll add a line referencing this discussion in the mice help where BLAS is mentioned. 

All the best, 

Gerko
