### ISSUE TITLE
Typo in FIMD formula 2.30

### ISSUE THREAD

**Issue by fengliu0tijmu** [amices/mice#401]
In the book "Flexible imputation of missing data" (page 48), the degree of freedom is the number of observations after accounting for the number of parameters in the model. The calculation of the degrees of freedom cannot be the same as for the complete data because part of the data is missing. The “old” formula (Rubin, 1987a, eq. 3.1.6) for the degrees of freedom can be written concisely as  Vold = (m-1)*(1+1/r^2) = (m-1)/lambda^2

I am wondering how to derive this equation, why (m-1)*(1+1/r^2) is equal to (m-1)/lambda^2?

I run the code below, and output the lambda and r, but I found 1+1/r^2 is not equal to 1/lambda^2. 

####################code####################
rm(list=ls())
library(mice)
imp <- mice(boys,m=3,maxit=5)
data<-complete(imp,'all')
var <- colnames(boys)
fx <- paste(var[-1], collapse = '+')
fx<-paste(var[1],fx,sep = '~')
fyx <- as.formula(fx)
fit <- with(imp, lm(formula(format(fyx))))
result=pool(fit)

com1 = 1/result$pooled$lambda^2
com2 = 1+(1/result$pooled$riv)^2

**Comment by stefvanbuuren** [comment]
Thanks for your note. You have discovered a typo in my book. 

Formula (3.1.6) in Rubin 1987 reads \nu = (m - 1)(1+1/r)^2. 
In my book (both 1st en 2nd Ed.) I wrote \nu = (m-1)(1+1/r^2), which puts the exponent at the wrong place.
In `mice` the calculations use (m - 1) / \lambda^2, so no worries there. 

I fear the fix in print will need to wait for a third edition.
