### ISSUE TITLE
Warning "invalid factor level, NA generated" by mice.mids()

### ISSUE THREAD

**Issue by stefvanbuuren** [amices/mice#410]
The following code produces a warning in `mice 3.13.8`:

``` r
library(mice, warn.conflicts = FALSE)
imp1 <- mice(nhanes2, maxit = 0, m = 1, seed = 1)
imp2 <- mice.mids(imp1, newdata = nhanes2[1, ])
#> Warning in `[<-.factor`(`*tmp*`, ri, value = 0.821221195098089): invalid factor
#> level, NA generated
#> 
#>  iter imp variable
#>   1   1  bmi  hyp  chl
```

<sup>Created on 2021-06-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The warning is does not appear for `nhanes` or for `newdata = nhanes2[1:2, ]`, so it occurs only when we have categorical data and one row in `newdata`.

**Comment by prockenschaub** [comment]
The error is thrown inside `mice::rbind.mids.mids` when `x$imp` and `y$imp` are combined. For some reason, the initial value chosen for `hyp` is a numeric value with decimals and not one of the factor levels `yes` or `no`. I will have a further look into this.

**Comment by stefvanbuuren** [comment]
Another way to generate the warning:

``` r
library(mice, warn.conflicts = FALSE)
imp <- mice(nhanes2[1, ], 
            remove.collinear = FALSE, remove.constant = FALSE, 
            maxit = 1, m = 1)
#> 
#>  iter imp variable
#>   1   1
#> Warning in `[<-.factor`(`*tmp*`, iseq, value = 1.16163441986097): invalid factor
#> level, NA generated
#>   bmi  hyp  chl
```

<sup>Created on 2021-06-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by stefvanbuuren** [comment]
The "last resort" initialization `imp[[j]][, i] <- rnorm(nrow(data))` in `initialize.imp()`does not work for categorical variables. A possible solution is to draw from the factor levels.

**Comment by stefvanbuuren** [comment]
`mice 3.13.9` solves the problem by taking random draws from the factor level. 

``` r
library(mice, warn.conflicts = FALSE)
packageVersion("mice")
#> [1] '3.13.9'

imp1 <- mice(nhanes2, maxit = 0, m = 1, seed = 1)
imp2 <- mice.mids(imp1, newdata = nhanes2[1, ])
#> 
#>  iter imp variable
#>   1   1  bmi  hyp  chl

imp <- mice(nhanes2[1, ], 
            remove.collinear = FALSE, remove.constant = FALSE, 
            maxit = 0, m = 1, seed = 1)
```

<sup>Created on 2021-06-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
