### ISSUE TITLE
Imputing sub-counts given a total count

### ISSUE THREAD

**Issue by mikejacktzen** [amices/mice#416]
Thanks for the mice package and great references.

I've looked around and so far it seems like there is no current way (or maybe I missed it) to tell the mice algorithm and helpers to impute a group of count variables with a multinomial count structure. 

Something like the below where N>1

```
id, N, n_a, n_b, n_c
1, 10, 2, 4, 4
2, 15, 5, 5, 5
3, 20, NA, NA, NA
```

Where N is the obs unit's grand count, but n_a, n_b, and n_c are the counts for the 3 respective categories a, b, and c

I do see references to using multinomial logit methods, where the "N" above would be N=1 and only one of n_a/b/c would be 1 while the others would be 0.

A use case situation is where we might observe the grand N for unit 3, and would like to impute their categorical counts.

Digging around, it looks like the vanilla `nnet::multinom()` can handle a response matrix of counts 
https://www.rdocumentation.org/packages/nnet/versions/7.3-16/topics/multinom

It is unclear to me how / where to tell mice to use this functionality.

Maybe this is a big ask, so I wouldn't expect this new feature to be available any time soon, but it would be very useful.

Thanks

**Comment by gerkovink** [comment]
This would be a compositional data structure. This structure does not have a representation in Euclidean space, but in Simplex space. One solution in mice is to convert the nested structure to ratios, imputed the ratios and decompose them into counts based on the totals. See e.g. [chapter 5 in here](https://dspace.library.uu.nl/bitstream/handle/1874/308699/vink.pdf).

**Comment by mikejacktzen** [comment]
Thanks @gerkovink looks like the keyword is *composition*  which lead me to

https://stefvanbuuren.name/fimd/mice-extensions.html#sec:blockvar

If I understand your suggestion here + chapter 5 + the fimd e-book section, it sounds like using the 'block' argument would help

0) convert observed raw categorical counts into observed ratios
1) blockwise impute the ratios (telling mice these categories should be grouped together)
2) use the imputed ratios to transform back to categorical counts

**Comment by mikejacktzen** [comment]
Actually, after reading more into it, I realize your 'predictive ratio matching' is a better and nuanced version of my heavy handed broad steps 0-3 above.

Is there some existing code that would could be wrapped into a 'prm' method that might be used as

```
mice(..., blocks=list(c('n_a','n_b','n_c', method ='prm')
```

I'm guessing the answer is no.

**Comment by gerkovink** [comment]
For simple compositions, you could use [passive imputation](https://www.gerkovink.com/mimp/Contents/Exercises/Day%202%20-%20Tuesday/Passive_Post_processing/Passive_imputation_post_processing.html).
