### ISSUE TITLE
NA values still there after imputing longitudinal data

### ISSUE THREAD

**Issue by indu-bodala** [amices/mice#419]
Hello, 

I have the following data

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/Indu/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/Indu/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

ID | Week | Observation
-- | -- | --
1 | 1 | 40
1 | 2 | 57
1 | 3 | 49
1 | 4 | 58
1 | 5 | 53
2 | 1 | 58
2 | 2 | 57
2 | 3 | 38
2 | 4 | 55
2 | 5 | 60
3 | 1 | 50
3 | 2 | 56
3 | 3 | 44
3 | 4 | 53
3 | 5 | 40
4 | 1 | 55
4 | 2 | NA
4 | 3 | 51
4 | 4 | 53
4 | 5 | 56
5 | 1 | 50
5 | 2 | 47
5 | 3 | 51
5 | 4 | 52
5 | 5 | 50
6 | 1 | 55
6 | 2 | 60
6 | 3 | 50
6 | 4 | NA
6 | 5 | 44
7 | 1 | 48
7 | 2 | NA
7 | 3 | 56
7 | 4 | 53
7 | 5 | 57
8 | 1 | 48
8 | 2 | 42
8 | 3 | NA
8 | 4 | 48
8 | 5 | 39
9 | 1 | 46
9 | 2 | 45
9 | 3 | 53
9 | 4 | 44
9 | 5 | NA

</body>

</html>

I have 5 timely observations for each subject and a total of 9 subjects. I am trying to impute the data using multilevel modeling. I specified pred(Obs, ID) = -2 and pred(Obs, time)=1 and then ran the imputation line with imp <- mice(raw, meth = 2l.pan, pred = pred, m = 10, maxit = 10, seed = 52711, print = FALSE). When I look at imp$data, I still find NAN values. Not sure what is happening here. Please advise.

Thank you!

**Comment by gerkovink** [comment]
Can you provide a [reprex](https://reprex.tidyverse.org)?

**Comment by stefvanbuuren** [comment]
Closing because lack of reprex.
