### ISSUE TITLE
logistic regression controlling for variables on imputed data

### ISSUE THREAD

**Issue by Phazha** [amices/mice#424]
Hi, I am trying to re-run a code that I had previously done on non-imputed logistic regression.

In this analysis "x" includes "age2" and "gender" alongside other variables, however, I am controlling for age and gender in the outcome.

The main issue that comes is when I try to create a matrix with confidence intervals with the expression "[n,]". as In R only objects with two dimensions (matrices and data.frames) can be referenced with object[ , n] references.

For the code I am trying to run below, the error message I get says "Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': error in evaluating the argument 'x' in selecting a method for function 'format': non-numeric argument to mathematical function".

I have read up and can't find alternative ways of running this code, or none work. Would really appreciate help.

Code:
#Variables of interest
df3 <- df2[, c("dem", "age2", "gender", "ethnic", "underwt", "hypert", "diab", 
               "depress", "deaf", "smoke_grp", "head_inj", "imd_decile")]

#Multiple imputation using mice
df4 <- mice(df3, m = 5, seed = 500)

#Logistic regression controlling for age and gender
model1 <- with(df4, glm(dem ~ x + age2 + gender))
mod1 <- summary(pool(model1), exponentiate = TRUE, conf.int = TRUE)

for(i in 1:length(varlist1)){
  print(varlist1[i])
  if(i<=2){    # age and gender - only need one parameter to output
    n <- length(mod1$estimate)-2
    OR <- format(round(mod1$estimate, 2), nsmall=2)[2:n]
    ci1 <- as.matrix(format(round(mod1$`2.5 %`, 2), nsmall=2)[2:n,])
    ci2 <- as.matrix(format(round(mod1$`97.5 %`, 2), nsmall=2)[2:n,])
  }
  
  if(i>=3){
    n <- length(mod1$estimate)
    n2 <- n-2
    OR <- format(round(mod1$estimate, 2), nsmall=2)[2:n2]
    ci1 <- as.matrix(format(round(mod1$`2.5 %`, 2), nsmall=2)[2:n2,])
    ci2 <- as.matrix(format(round(mod1$`97.5 %`, 2), nsmall=2)[2:n2,])
  }
  
  
  if(i<=2){   # Age and gender only have one level each and R outputs this differently compared to multi-level vars
    ci1 <- ci1[1]
    ci2 <- ci2[2]
  }
  
  if(i>=3){
    ci1 <- ci1[,1]
    ci2 <- ci2[,2]
  }
  
  out <- paste0(OR, " (", ci1, ", ", ci2, ")")
  
  if(i==1){
    out2 <- out
  }
  if(i>1){
    out2 <- append(out2, out)
  }
}

**Comment by stefvanbuuren** [comment]
I'm sorry. Cannot run this code. Use the `reprex` package to create a decent example.

**Comment by Phazha** [comment]
The above code does not run, but is rather my attempt at running a script that I had successfully done before using non imputed data. The issue arises in adapting the script below, to a mira object. I would be deeply appreciative on your insight on how to do so.

Original script:
varlist1 <- c("age2", "gender", "ethnic", "imd_decile", "underwt", "hypert", "diab", "depress", 
              "deaf", "smoke_grp", "head_inj")

varlist2 <- c("age2", rep("gender",2), rep("ethnic",5), rep("imd_decile",11), rep("underwt",4),  
              rep("hypert",4), rep("diab",4), rep("depress",4), rep("deaf",4), rep("smoke_grp",4), rep("head_inj",4))

varlist3 <- as.factor(c("Age", "Female", "Male", "White", "Black", "S.Asian", "Other", "Unknown", "1", "2", "3", "4", 
                        "5", "6", "7", "8", "9", "10", "Unknown",  
                        rep(c("Never", "Yes", "Post-Dem", "Unknown"),1), 
                        rep(c("Normal", "Yes", "Post-Dem", "Unknown"),4), 
                        "Never", "Ex-", "Current", "Unknown",
                        rep(c("Normal", "Yes", "Post-Dem", "Unknown"),1)))

out <- rep(NA, length(varlist2))

# 2. Adjusted for age and gender models script used on none imputed data:
for(i in 1:length(varlist1)){
  print(varlist1[i])
  df$x <- df[, varlist1[i]]
  mod2 <- glm(dem ~ x + age2 + gender, family=binomial, data=df)
  summary(mod2)
  
  if(i<=2){    # age and gender - only need one parameter to output
    n <- length(mod2$coefficients)-2
    OR <- format(round(exp(mod2$coefficients), 2), nsmall=2)[2:n]
    ci <- as.matrix(format(round(exp(confint(mod2)), 2), nsmall=2)[2:n,])
  }
  
  if(i>=3){
    n <- length(mod2$coefficients)
    n2 <- n-2
    OR <- format(round(exp(mod2$coefficients), 2), nsmall=2)[2:n2]
    ci <- as.matrix(format(round(exp(confint(mod2)), 2), nsmall=2)[2:n2,])
  }
  
  
  if(i<=2){   # Age and gender only have one level each and R outputs this differently compared to multi-level vars
    ci1 <- ci[1]
    ci2 <- ci[2]
  }
  
  if(i>=3){
    ci1 <- ci[,1]
    ci2 <- ci[,2]
  }
  
  out <- paste0(OR, " (", ci1, ", ", ci2, ")")
  
  if(i==1){
    out2 <- out
  }
  if(i>1){
    out2 <- append(out2, out)
  }
  
  df$x <- NULL
  rm(n); rm(n2); rm(OR); rm(ci); rm(ci1); rm(ci2)
}

out3 <- c(out2[1], "1", out2[2], "1", out2[3:6], "1", out2[7:16], "1", out2[17:19], "1", out2[20:22], "1", out2[23:25], "1", out2[26:28], "1", out2[29:31], "1", out2[32:34], "1", out2[35:37])    

adj_mods1 <- out3

**Comment by stefvanbuuren** [comment]
I am sorry. We cannot help you if we have no reprex.
