### ISSUE TITLE
Avoid changing global .Random.seed

### ISSUE THREAD

**Issue by weiyaw** [amices/mice#426]
Hi,

Would you consider using `withr::local_seed` in `mice()` rather than `set.seed`?

Currently `set.seed` sets `.Random.seed` in the users' global environment which can result in unintended results and bugs.

Regards,

Kenyon

**Comment by stefvanbuuren** [comment]
Thanks for your suggestion of a neater alternative.

I created a branch `randomseed` that isolates the seed streams used in the `mice()` and `mice.mids()` functions. The random number state is reset to the initial state on completion of `mice(...)` or `mice.mids(...)`, so both functions do not interfere anymore with the calling code, e.g., 

```r
context("mice: local random stream")

set.seed(1)
a <- runif(10)

set.seed(1)
b1 <- runif(6)

imp <- mice(nhanes, maxit = 0, seed = 82, print = FALSE)
imp2 <- mice.mids(imp, maxit = 1, print = FALSE)

b2 <- runif(4)

test_that("mice and mice.mids use a local random stream", {
  expect_equal(a, c(b1, b2))
})
``` 

As long as the branch exists, install by 

```r
devtools::install_github(repo = "amices/mice@randomseed")
```

I did not look at the parallel functionality in the package.

Does this work for you?

**Comment by stefvanbuuren** [comment]
PR #432 implements the local seed in the master version.
