### ISSUE TITLE
[2l.lmer] Error in Xi %*% beta.star : non-conformable arguments

### ISSUE THREAD

**Issue by shind10** [amices/mice#427]
Dear Dr.Van buuren

I was wondering why 2l.lmer method in mice doesn't work for some dataset. 
It worked fine with data1 but I don't understand why it does not work for data2. 
It showed me error msg that "Error in Xi %*% beta.star : non-conformable arguments"
Only the difference between data1 and data2 are missing rate (Y-W1-W2(20%-20%-20% missing) for data1 where Y-W1-W2(20%-40%-40% missing) for data2).
Attached are dataset and reproducible code. 

[data1.csv](https://github.com/amices/mice/files/7071326/data1.csv)
[data2.csv](https://github.com/amices/mice/files/7071328/data2.csv)

[Data1]
y20w20_del=read.csv("https://github.com/amices/mice/files/7071326/data1.csv")
y20w20_del$X=NULL
pred = make.predictorMatrix(y20w20_del)
pred["Yij",]=c(0,3,3,-2)
pred["W1ij",]=c(3,0,3,-2)
pred["W2ij",]=c(3,3,0,-2)
pred["id",]=c(0,0,0,0)

imp = mice(y20w20_del, pred=pred, meth="2l.lmer", m=10, print=FALSE)

[Data2]
y20w20_del=read.csv("https://github.com/amices/mice/files/7071326/data2.csv")
y20w20_del$X=NULL
pred = make.predictorMatrix(y20w20_del)
pred["Yij",]=c(0,3,3,-2)
pred["W1ij",]=c(3,0,3,-2)
pred["W2ij",]=c(3,3,0,-2)
pred["id",]=c(0,0,0,0)

imp = mice(y20w20_del, pred=pred, meth="2l.lmer", m=10, print=FALSE)

**Comment by shind10** [comment]
Found out that it worked fine after I remove the cluster with only one observations. Still don't understand why that cause non-conformable matrix. If anyone knows please let me know.

**Comment by stefvanbuuren** [comment]
One cause could be a forgotten `drop = FALSE` clause in line 147 of `mice.impute.2l.lmer.R`. Unfortunately, my system does not reproduce the error. Can you confirm that the error disappears if you set 

```r
Xi <- Xobs[xobs[, clust] == jj, drop = FALSE]
```

at that line?

**Comment by stefvanbuuren** [comment]
Perhaps you're running the CRAN version and issue #384 might have solved this. Could you check after installing the dev version of `mice` using

```r
 devtools::install_github(repo = "amices/mice")
```

**Comment by stefvanbuuren** [comment]
Closing in advance to reactions. Please feel free to reopen as needed.
