### ISSUE TITLE
mice and stepwise model selection with glmer.nb

### ISSUE THREAD

**Issue by ajw11** [amices/mice#428]
I'm having an issue with using glmer.nb and the following stepwise model selection process below (from https://stefvanbuuren.name/fimd/sec-stepwise.html) 

data <- boys[boys$age >= 8, -4]
imp <- mice(data, seed = 28382, m = 10, print = FALSE)
scope <- list(upper = ~ age + hgt + wgt + hc + gen + phb + reg,
              lower = ~1)
expr <- expression(f1 <- lm(tv ~ 1),
                   f2 <- step(f1, scope = scope))
fit <- with(imp, expr)

I want to fit a negative binomial model with a random intercept, but when I run code similar to this (not the same data obviously), I receive an error after I run "fit<-with (imp,expr)" for not having the data specified in the expression ("expr") glmer.nb(y~x1+(1|intercept)) part of the code (the error says "data=*"?). It wants me to have something like glmer.nb(y ~x1+(1|intercept), data=dataset). 

This is not a problem if I swap glmer.nb for glmer, lm, or lmer. These models do not require the data to be specified, as it is not specified for the model above ( lm(tv ~ 1)).Is there a workaround for this?

**Comment by stefvanbuuren** [comment]
Does `data = data.i` instead of `data = dataset` perhaps work?

**Comment by ajw11** [comment]
I will try it tomorrow I don’t have access to the data right now. Will this cause problems with the methodology?  (ie, fit to complete dataset vice fitting to m datasets first then combine?)

**Comment by ajw11** [comment]
In my data set, my dataframe is called df:

df.i gives me the following message: 

Bad 'data' but variables found in environment of formula: try specifying 'formula' as a formula rather than a string in original model.

If I only use data=df, the message says:

No method for assigning subsets of this S4 class

**Comment by stefvanbuuren** [comment]
Did you try `data = data.i` or perhaps `data = get("data.i")` in your `glmer.nb(...)` call?

**Comment by ajw11** [comment]
Is “data” the name of the data frame?

**Comment by stefvanbuuren** [comment]
The name of the data frame of the i'th imputed data set created in `with.mids()` is `"data.i"`, so we're trying to input that into the analysis with `glmer.nb(..., data = data.i)`. I don't know whether it works, but it's easy to try.

**Comment by ajw11** [comment]
No, "data.i" gives the "bad data" error

**Comment by stefvanbuuren** [comment]
Ok, then use `complete()` to extract the m imputed data sets, and run your complete-data model by hand on each of these.

**Comment by ajw11** [comment]
Ok. The final pooling would need to be done by hand, too?

**Comment by stefvanbuuren** [comment]
Yes, I fear so..

**Comment by HywelMJ** [comment]
Where the dataframe is 'df', the following seems to work for me: with(df, glmer.nb(......., data = df$data$i)
