### ISSUE TITLE
Repeated coefficients when applying polr in with() function for ordinal data 

### ISSUE THREAD

**Issue by AJasz** [amices/mice#430]
Hi @stefvanbuuren & teams,

I'm using mice version  3.13.0. My codes are upgraded from #390 . 
However, the results yielded  the repeated coefficients for **Em6** and **SN1**
How to get only one coefficient for **Em6** and **SN1**?

My data is attached
[dat.csv](https://github.com/amices/mice/files/7189094/dat.csv)
These are my recent codes:

```
library(mice)
library(nnet)
library(mitools)
library(MASS)

dat <- read.csv(file = 'dat.csv')
female<-dat$Gender== 1

NaFmE6 <- sum(female) * 0.2
NaFmSN1 <- sum(female) * 0.2

set.seed(1)
dat$Em6[sample(which(female),NaFmE6)]<-NA   ####these missing values  based on missing rate
dat$SN1[sample(which(female),NaFmSN1)]<-NA  ##these missing values  based on missing rate
dat1<-dat

dat$Em6<- as.factor(dat$Em6)
dat$SN1<- as.factor(dat$SN1)
dat$Perspective<- as.factor(dat$Perspective)

imp <- mice(dat, maxit=0)

predM <- imp$predictorMatrix
meth <- imp$method
meth[c("Em6","SN1")] <- "polr"

predM[,"Gender"]<-0
predM[,"Course"]<-0
predM[,"Region"]<-0
predM[,"Age"]<-0
predM[,"Em5"]<-0
predM[,"SN2"]<-0
predM[,"SN3"]<-0
predM[,"SN6"]<-0
predM[,"SN2"]<-0
predM[,"SN3"]<-0
predM[,"SN6"]<-0
predM[,"Ec1"]<-0
predM[,"Ec2"]<-0
predM[,"Ec3"]<-0
predM[,"Ec4"]<-0
predM[,"Ec5"]<-0

imp2 <- mice(dat, m = 5,
             predictorMatrix = predM,
             method = meth, print =  FALSE)

imputed <- complete(imp2)

mod<- with(imp2, polr(Perspective ~ Em1 + Em2 + Em3 +Em4+Em6+ SN1+SN4+SN5+Ec6 ,model=TRUE,Hess=TRUE))
pool(mod)

```
These are the results:

Class: mipo    m = 5 
   term m     estimate       ubar            b          t dfcom       df          riv       lambda        fmi
1   Em1 5  -1.28074027 0.21799657 4.847721e-03 0.22381383   236 219.4926 0.0266851242 0.0259915368 0.03474696
2   Em2 5  -0.04720822 0.19324352 1.041189e-02 0.20573779   236 182.7710 0.0646555862 0.0607291100 0.07084125
3   Em3 5   0.45583049 0.16301073 9.843353e-03 0.17482275   236 174.7043 0.0724616303 0.0675657089 0.07805993
4   Em4 5   0.59719244 0.07893452 4.919643e-04 0.07952488   236 231.5468 0.0074790750 0.0074235537 0.01588734
**5  Em62 5  -0.52030185 1.40676989 7.230280e-02 1.49353325   236 185.8640 0.0616755869 0.0580926864 0.06806714
6  Em63 5  -0.98565729 1.58181902 9.974963e-02 1.70151857   236 171.4199 0.0756720909 0.0703486607 0.08100859
7  Em64 5  -0.31559935 2.44959511 1.344381e-01 2.61092083   236 181.5236 0.0658581152 0.0617888200 0.07195783
8  Em65 5  -1.44205591 2.22079939 2.649453e-01 2.53873370   236 113.5636 0.1431621066 0.1252334255 0.14024268
9  SN12 5 -16.14069626 0.38604734 2.269150e-02 0.41327713   236 176.6867 0.0705348679 0.0658875017 0.07628463
10 SN13 5 -15.15320320 0.45973742 2.887255e-02 0.49438448   236 171.7352 0.0753627178 0.0700812076 0.08072496
11 SN14 5 -16.08964032 0.51171942 8.526844e-03 0.52195163   236 224.4888 0.0199957492 0.0196037574 0.02822305
12 SN15 5 -15.35239687 0.59848461 1.400016e-02 0.61528480   236 218.3701 0.0280712110 0.0273047341 0.03609269**
13  SN4 5   0.31816063 0.08868064 7.213121e-05 0.08876719   236 233.7839 0.0009760581 0.0009751064 0.00941339
14  SN5 5  -0.59831944 0.07435090 1.276588e-03 0.07588281   236 224.0659 0.0206037314 0.0201877876 0.02881799
15  Ec6 5  -0.22925106 0.05419322 3.051940e-04 0.05455945   236 231.8471 0.0067579081 0.0067125453 0.01517156
16  2|3 5 -21.07693929 2.50257785 1.132205e-02 2.51616431   236 232.3672 0.0054289859 0.0053996712 0.01385115
17  3|4 5 -19.77296385 2.22969365 1.232959e-02 2.24448916   236 231.8968 0.0066356693 0.0065919274 0.01505018
18  4|5 5 -18.61949397 2.05977511 1.328012e-02 2.07571126   236 231.4364 0.0077368372 0.0076774382 0.01614304

But, if I change all the predictors as factor; `dat[,1:23]<- lapply(dat[,1:23], as.factor)`, i will get an error like this :

```
Error in optim(s0, fmin, gmin, method = "BFGS", ...) : 
  initial value in 'vmmin' is not finite
In addition: Warning message:
glm.fit: fitted probabilities numerically 0 or 1 occurred 


```

**Comment by stefvanbuuren** [comment]
> How to get only one coefficient for Em6 and SN1?

I guess you have a coefficient per category because you coded 

```r
dat$Em6<- as.factor(dat$Em6)
dat$SN1<- as.factor(dat$SN1)
```

**Comment by stefvanbuuren** [comment]
I am sorry. I have no idea what you're trying to do, or what your question is, so I am closing.
