### ISSUE TITLE
Blocks argument generates different results

### ISSUE THREAD

**Issue by lauosgom** [amices/mice#444]
Currently, we are using the mice package to input missing functional data of plant species. However, when we use the argument blocks we get differences when we only specify one block or two; see example ( blocks = “chl” or c(“chl”, “bmi”)) and I would like to ask you that adding clocks to this argument implies that the other block has an influence on the other one?.

We have been using the same predictor matrix for both cases (only one block and multiple blocks) and we keep getting different results. Do you have any idea why is this happening? Thank you very much for your time.

**Comment by stefvanbuuren** [comment]
This is expected behaviour. 

The documentation says *Only variables whose names appear in blocks are imputed*, so solutions with `blocks = "chl"` and `blocks = c(“chl”, “bmi”)` will differ.

**Comment by lauosgom** [comment]
Thank you for the answer. However, the imputation of 'chl' by itself is different from the imputation of 'chl' when it is included in a block with 'bmi'. What is the reason for this? does bmi have influence on chl if they are in the same block?
