### ISSUE TITLE
Undocumented dependency withr >=2.4.0

### ISSUE THREAD

**Issue by str-amg** [amices/mice#445]
Hi there, don't have time to document this as thoroughly as I'd like, but I have some strong indicia that the latest version of mice (v3.14.0) has a dependency on withr >=2.4.0, which is not specified in the DESCRIPTION file. Specifically I encountered issues installing mice with withr v2.3.0 below:
```R
> ** byte-compile and prepare package for lazy loading
> Error: object 'local_seed' is not exported by 'namespace:withr'
> Execution halted                     
> ERROR: lazy loading failed for package 'mice'
``` 

which was easily addressed by updating withr to the latest CRAN version (v2.4.2). I note that withr is an explicit dependency listed in the DESCRIPTION but has no version requirement. 

~I'm sorry I haven't been able to dig up the reference to either local_seed's use in this package, nor when between 2.3.0 and 2.4.2 local_seed became an exported function.~ Update -- it turns out withr put it [right in NEWS:](https://github.com/r-lib/withr/blob/f25fb5ff6b6dc8405a9384814c3a61f67a71d32a/NEWS.md#withr-240) -- the dependency is on `withr (>=2.4.0)` Please let me know if further documentation of the error is needed.

**Comment by stefvanbuuren** [comment]
Thanks for alerting and the helpful info.

This is a new dependency. I wasn't aware that `withr` before 2.4.0 (January 2021)  have this problem. Commit b85551e adds the version (>= 2.4.0) on the `withr` dependency.

Here's what I added to news:

>>> @str-amg reported that the new dependency on `withr` package should have version 2.4.0  (published in January 2021) or higher. Version `withr 2.30.0` and before may give `Error: object 'local_seed' is not exported by 'namespace:withr'`. Either update manually, or install the patched version `mice 3.14.1` from GitHub. (#445)

Hope this solves the problem.

**Comment by stefvanbuuren** [comment]
Reopening to give it higher visibility.

**Comment by gerkovink** [comment]
@stefvanbuuren I've pinned the issue. You can close if you want - it'll remain at the top of the issues page
