### ISSUE TITLE
Mistake in vignette #2

### ISSUE THREAD

**Issue by george-kan** [amices/mice#446]
I am going through the vignettes for the package (which are wonderful and thank you very much!). In the second one: https://www.gerkovink.com/miceVignettes/Ad_hoc_and_mice/Ad_hoc_methods.html I think there is an issue here: 

![image](https://user-images.githubusercontent.com/56187121/143671115-c616d38f-c802-489b-913a-c7f9bc626c76.png)

**Comment by stefvanbuuren** [comment]
Thanks for your note. You're right.

The "zero rows" in the `predictorMatrix` used to be the case in older versions of `mice`. This is a leftover that we should take out.

**Comment by gerkovink** [comment]
Will change.
