### ISSUE TITLE
Question about blocks in mice

### ISSUE THREAD

**Issue by lauosgom** [amices/mice#450]
This is expected behaviour. 

The documentation says *Only variables whose names appear in blocks are imputed*, so solutions with `blocks = "chl"` and `blocks = c(“chl”, “bmi”)` will differ.

_Originally posted by @stefvanbuuren in https://github.com/amices/mice/issues/444#issuecomment-978171034_

Thank you @stefvanbuuren for the answer. However, the imputation of 'chl' by itself is different from the imputation of 'chl' when it is included in a block with 'bmi'. What is the reason for this? does bmi have influence on chl if they are in the same block?

**Comment by stefvanbuuren** [comment]
"is different" can mean many things. `mice` uses a random generator, so "differences" are expected in general. 

Please provide a reproducible example, exactly as possible outlining what you think would be the problem.
