### ISSUE TITLE
Bug in test.impute() FIMD2, page 54 [SOLVED]

### ISSUE THREAD

**Issue by stefvanbuuren** [amices/mice#453]
Jesper Lundquist alerted me that the simulation script on page 54 of **Flexible Imputation of Missing Data, Second Edition** does not run properly.

After some digging, I found the problem in the `test.impute()` function. 

```{r}
test.impute <- function(data, m = 5, method = "norm", ...) {
  imp <- mice(data, method = method, m = m, print = FALSE, ...)
  fit <- with(imp, lm(y ~ x))
  tab <- summary(pool(fit), "all", conf.int = TRUE)
  as.numeric(tab["x", c("estimate", "2.5 %", "97.5 %")])
}
```

The problem is a syntax error in the last line. The corrected function is

```{r}
test.impute <- function(data, m = 5, method = "norm", ...) {
  imp <- mice(data, method = method, m = m, print = FALSE, ...)
  fit <- with(imp, lm(y ~ x))
  tab <- summary(pool(fit), "all", conf.int = TRUE)
  as.numeric(tab[tab$term == "x", c("estimate", "2.5 %", "97.5 %")])
}
```

Still wondering though why the first script ran in the first place.

**Comment by gerkovink** [comment]
I had this too at one point. I believe it is related to a format/class change in the object returned through `broom`.
