### ISSUE TITLE
midastouch: use neff option

### ISSUE THREAD

**Issue by sff06** [amices/mice#458]
I use midastouch to impute missing values. I further would like to apply the bias correction factor presented by Gaffert et al. (2016, eq. 4) that originates from Parzen et al. (2005). However, I am not sure how to do this in mice. In line with your R code instructions I created a new environment (PFLenv) and added to mice(..., neff = "PLFenv"). Would that suffice to use the correction factor?

I am having doubts because I ran mice(..., method = 'midastouch') with and without neff = "PLFenv", but the results were identical. Sample size is N = 227. Missingness in key variables is 16%.

Thank you for any support!

Best,
Stanley

**Comment by stefvanbuuren** [comment]
This is best answered by Philipp Gaffert or Florian Meinfelder. Both are `mice` contributors.

**Comment by sff06** [comment]
Thank you for your response! Both are not mentioned under constributors. So I guess they won't be able to notice my issue. I will try to contact them via other means and hopefully can post a clarification of the issue.

**Comment by stefvanbuuren** [comment]
They are package contributors. See DESCRIPTION.

**Comment by PhilippGaffert** [comment]
With every execution, the correction factor is calculated and added to your specified environment. The correction factor is not considered in the pooling that is done by mice. If you wanted to use these correction factors, you would need to write your own pooling. Be aware that the correction factor that is derived in Gaffert et al. 2018 is only applicable to means. Correction factors for more complex analysis models are not yet developed to the best of my knowledge.
Whatever you discover in this process, I'd be keen to learn about.

**Comment by sff06** [comment]
Thank you for your response and the note regarding the mean! Currently, I focus on robust correlations and differences of trimmed means, so I won't be using the PLF correction anymore and just rely on the midastouch without this correction.
