### ISSUE TITLE
Fail to impute categorical variables - loggedEvents: constant

### ISSUE THREAD

**Issue by xiw588** [amices/mice#461]
Hi, I am trying to impute two ordered categorical variables. The dataset I input to mice contains seven columns and only two had missingness. groups had 30% missingness and PS had 4 missingness. 

I tried to impute using the following code 
a<-mice(CI_impute,m=3,diagnostics = TRUE,method = 'polr') 

Below is the logged events I got.  The is a numeric variable called age in this dataset and it is complete. I am wondering where does the problem come. Can you please help me with this? Thank you!
> a$loggedEvents
  it im dep     meth               out
1  0  0     constant            groups
2  0  0     constant               Sex
3  0  0     constant         histology
4  0  0     constant               PS
5  0  0     constant            therapy
6  0  0     constant              smok

**Comment by gerkovink** [comment]
First, is the measurement level of your variables correctly coded? Second, can you create a `reprex`? Without a reproducible example it is challenging to be of help.

**Comment by gerkovink** [comment]
Assuming this has been solved. Feel free to re-open.
