### ISSUE TITLE
Add informative error message to `mcar()` function for too little missing data patterns

### ISSUE THREAD

**Issue by hanneoberman** [amices/mice#467]
If someone were to ignore the function documentation and just ran the `mcar()` function on a dataset with one missing data pattern, the error message would be: 

```
Error in mcar.data.frame(popmis2) : object 'idpats' not found.
```
It may be nice to make this more informative by adding the following to the `mcar()` function:
```
  if(nrow(pats) < 4L){
    stop("This MCAR test requires two or more missing data patterns.")
  }
```
@cjvanlissa Do you think that would make sense?

**Comment by cjvanlissa** [comment]
Absolutely! Are you on this, or do you need me to make the change>?
