### ISSUE TITLE
Why does the problem of circularity during passive imputation lead to strange imputations and non-convergence?

### ISSUE THREAD

**Issue by jeyabbalas** [amices/mice#472]
Thank you to this community for building such a comprehensive and useful tool!

I went through the MICE vignettes and had a question from it. [In vignette 4 "Passive imputation and post-processing", please scroll down to step 8](https://www.gerkovink.com/miceVignettes/Passive_Post_processing/Passive_imputation_post_processing.html). Pay attention to the figure in that step. This vignette warns us against circumstances that can lead to such strange imputations (BMIs well over 100s). The vignette describes this as "the problem of circularity", which I have summarized below.

The example introduces a passive imputation rule for imputing BMI values as follows:

```
meth["bmi"]<- "~ I(wgt / (hgt / 100)^2)"
imp <- mice(boys, meth=meth, print=FALSE)
```

So, the variable `bmi` now depends upon variables `wgt` and `hgt`. However, from the prediction matrix, we see that variables `wgt` and `hgt` still cyclicly depend upon `bmi`. This is described as the problem of circularity.

```
pred<-ini$pred
pred

##     age hgt wgt bmi hc gen phb tv reg
## age   0   1   1   1  1   1   1  1   1
## hgt   1   0   1   1  1   1   1  1   1
## wgt   1   1   0   1  1   1   1  1   1
## bmi   1   1   1   0  1   1   1  1   1
## hc    1   1   1   1  0   1   1  1   1
## gen   1   1   1   1  1   0   1  1   1
## phb   1   1   1   1  1   1   0  1   1
## tv    1   1   1   1  1   1   1  0   1
## reg   1   1   1   1  1   1   1  1   0
```

The suggested fix is simple. Simply break the cycle. Make sure that `wgt` and `hgt` no longer depends upon `bmi`, as shown below.

```
pred[c("hgt", "wgt"), "bmi"] <- 0
```

I am unable to understand why the problem of circularity leads to such strange imputations and non-convergence? When I use the default PMM imputation method, I always impute realistic values for `hgt` and `wgt` sampled directly from similar examples in the data. How then can I get such bizarre BMIs like in the 300s? Why does this problem not manifest when we don't use passive imputation but have cyclic dependencies?

**Comment by gerkovink** [comment]
Let's assume that you first impute a large `hgt` based on the predictors. Since `hgt` and `wgt` are strongly correlated, a large `wgt` is likely to be imputed. Then, `bmi` is deductively calculated, and the cycle reiterates. A large BMI will lead to a specific `hgt/wgt` ratio, and so on. Because there are too many degrees of freedom, the system can in theory go into outer space for one or more chains.

**Comment by jeyabbalas** [comment]
Thank you for your prompt reply @gerkovink !

How is it even possible to even get a BMI > 300 using PMM? PMM imputes real values from the data for `hgt` and 'wgt' in the above scenario. In the `boys` dataset, the max value of `hgt = 198` and `wgt = 117.8`. So, in theory, the largest possible value for BMI can be: `bmi = (wgt / (hgt / 100)^2) = (117.8 / (198 / 100)^2) = 29.95`. How do we get such large values imputed for `bmi`?

**Comment by gerkovink** [comment]
Passive imputation does calculate the imputed value for BMI in your example
deductively, not by PMM.

**Comment by jeyabbalas** [comment]
Right, but `wgt` and `hgt` is still being imputed using PMM, right? In my previous reply, I am computing BMI deductively using the formula for BMI.

**Comment by gerkovink** [comment]
But hgt and wgt can be imputed such that the highest wgt and lowest hgt
lead to unrealistically large BMI; simply because their imputations are
influenced by the unrestricted BMI from the previous iteration.
