### ISSUE TITLE
Reference Based Imputation

### ISSUE THREAD

**Issue by LeaSchuurmans** [amices/mice#476]
Hallo,

I was wondering if there is a way to do reference-based imputation like J2R according to [Carpenter (2013) ](https://www.tandfonline.com/doi/abs/10.1080/10543406.2013.834911?journalCode=lbps20) with mice. Are there any possibilities?

Thank you,
Lea

**Comment by gerkovink** [comment]
Hi Lea, 

You're in luck: As of yesterday there is a whole package devoted to reference based imputation on CRAN: [`rbmi`](https://cran.r-project.org/web/packages/rbmi/index.html). 

All the best, 

Gerko

**Comment by LeaSchuurmans** [comment]
@gerkovink thank you very much, this seems to do exactly what I was looking for! Even though it would be more convenient to implement the J2R in my mice routine as @stefvanbuuren has mentioned.

Thank you for your replies!
