### ISSUE TITLE
Error when applying bycases = FALSE in ampute

### ISSUE THREAD

**Issue by fmartinssp** [amices/mice#503]
I'm trying to run the ampute() function with bycases = FALSE, to the proportion of missingness is defined in terms of cells. I found the following error:

"Proportion of missing cells is too large in combination with the desired number of missing variables"

I'm using the Iris dataset and the command is "missing <- ampute(Iris,mech = "MCAR",bycases = FALSE)".

Could anybody help me?

![ampute](https://user-images.githubusercontent.com/38142443/194756068-8790ff2a-65dc-4071-a45c-68e7beebbade.png)

**Comment by fmartinssp** [comment]
In addition, I am using the package 'mice' version 3.14.0

**Comment by stefvanbuuren** [comment]
I think the `bycases = FALSE` is not appropriate for continuous data.

Error: Proportion of missing cells is too large in combination with the desired number of missing variables
