### ISSUE TITLE
Segmentation fault on Apple arm64 for md.pattern()

### ISSUE THREAD

**Issue by gH2AX** [amices/mice#513]
I load a dataset in the variable 'ww', then when i call md.pattern(ww), my R session crashes with the following error message:

```
*** caught segfault ***
address 0x0, cause 'invalid permissions'

Traceback:
 1: grDevices::dev.capabilities("semiTransparency")
 2: supports.transparent()
 3: mdc(1)
 4: ifelse(R[nrow(R):1, ], mdc(1), mdc(2))
 5: md.pattern(ww)
```

**Comment by gerkovink** [comment]
Can you make a [reprex](https://reprex.tidyverse.org/), because I cannot reproduce.

**Comment by gH2AX** [comment]
It seems reprex has its own issues..

```
> reprex(md.pattern(iris.mis))
ℹ Rendering reprex...
Error in `reprex_render()`:
! This reprex appears to crash R. Call `reprex()` again with `std_out_err = TRUE` to get more info.
Run `rlang::last_error()` to see where the error occurred.
> reprex(md.pattern(iris.mis), std_out_err = TRUE)
ℹ Rendering reprex...
sh: +RTS: command not found
Error: pandoc document conversion failed with error 127
In addition: Warning message:
In system(command) : error in running command
```

**Comment by gH2AX** [comment]
It's unspecific, I tried various datasets. But here's one expample:

The iris dataset is a built-in dataset in R.
I run the following commands:
```
library(missForest)
library(mice)

iris.mis = prodNA(iris, noNA = 0.1)
ris.mis = subset(iris.mis, select=-c(Species))

md.pattern(iris.mis)
```

*** caught segfault ***

**Comment by gH2AX** [comment]
Still on Monterey.. what's the issue with tools? And how would I re-install it? It's a base-package and cannot be removed.

**Comment by gerkovink** [comment]
Can also not reproduce:

``` r
library(missForest)
library(mice)
iris.mis = prodNA(iris, noNA = 0.1)
iris.mis = subset(iris.mis, select=-c(Species))
md.pattern(iris.mis)
```

![](https://i.imgur.com/Rdgc18l.png)

    #>    Sepal.Width Sepal.Length Petal.Length Petal.Width   
    #> 96           1            1            1           1  0
    #> 14           1            1            1           0  1
    #> 11           1            1            0           1  1
    #> 3            1            1            0           0  2
    #> 10           1            0            1           1  1
    #> 1            1            0            1           0  2
    #> 2            1            0            0           1  2
    #> 9            0            1            1           1  1
    #> 2            0            1            0           1  2
    #> 2            0            0            1           1  2
    #>             13           15           18          18 64

    sessionInfo()
    #> R version 4.2.1 (2022-06-23)
    #> Platform: x86_64-apple-darwin17.0 (64-bit)
    #> Running under: macOS Big Sur ... 10.16
    #> 
    #> Matrix products: default
    #> BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
    #> LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
    #> 
    #> locale:
    #> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    #> 
    #> attached base packages:
    #> [1] stats     graphics  grDevices utils     datasets  methods   base     
    #> 
    #> other attached packages:
    #> [1] mice_3.14.8    missForest_1.5
    #> 
    #> loaded via a namespace (and not attached):
    #>  [1] Rcpp_1.0.9           compiler_4.2.1       pillar_1.8.1        
    #>  [4] highr_0.9            iterators_1.0.14     tools_4.2.1         
    #>  [7] rngtools_1.5.2       digest_0.6.30        lattice_0.20-45     
    #> [10] evaluate_0.17        lifecycle_1.0.3      tibble_3.1.8        
    #> [13] pkgconfig_2.0.3      rlang_1.0.6          doRNG_1.8.2         
    #> [16] reprex_2.0.2         foreach_1.5.2        DBI_1.1.3           
    #> [19] cli_3.4.1            rstudioapi_0.14      yaml_2.3.6          
    #> [22] parallel_4.2.1       xfun_0.34            fastmap_1.1.0       
    #> [25] withr_2.5.0          stringr_1.4.1        dplyr_1.0.10        
    #> [28] knitr_1.40           generics_0.1.3       fs_1.5.2            
    #> [31] vctrs_0.5.0          grid_4.2.1           tidyselect_1.2.0    
    #> [34] glue_1.6.2           R6_2.5.1             fansi_1.0.3         
    #> [37] rmarkdown_2.17       tidyr_1.2.1          purrr_0.3.5         
    #> [40] magrittr_2.0.3       backports_1.4.1      codetools_0.2-18    
    #> [43] htmltools_0.5.3      itertools_0.1-3      assertthat_0.2.1    
    #> [46] randomForest_4.7-1.1 utf8_1.2.2           stringi_1.7.8       
    #> [49] broom_1.0.1

<sup>Created on 2022-11-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by gerkovink** [comment]
Since it seems to be isolated to your R instance, and not to `aarch64-apple-darwin20 (64-bit)` in general; perhaps a fresh install of the latest R framework would suffice. 

@gH2AX You are not by any chance running R through Anaconda?

**Comment by gH2AX** [comment]
> @gH2AX You are not by any chance running R through Anaconda?

No, I am not running Anaconda.

> […] you need the proper compilers if you are installing from source […]

I only tried to compile from source once this error emerged..

**Comment by gerkovink** [comment]
I have a feeling that a clean install of the most recent R framework and RStudio would fix. Have you tried this?

The error you receive is not related to 'mice', but stems from 'grDevices::dev.capabilities("semiTransparency")'.

**Comment by stefvanbuuren** [comment]
Yes agree. What happens if you run

``` r
z <- grDevices::dev.capabilities("semiTransparency")
class(z)
#> [1] "list"
z
#> $semiTransparency
#> [1] TRUE
```

<sup>Created on 2022-11-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by gH2AX** [comment]
> Yes agree. What happens if you run
> 
> ```r
> z <- grDevices::dev.capabilities("semiTransparency")
> class(z)
> #> [1] "list"
> z
> #> $semiTransparency
> #> [1] TRUE
> ```
> 
> Created on 2022-11-11 with [reprex v2.0.2](https://reprex.tidyverse.org)

An empty (white) Quartz window opens. And I get the same output as you.
Btw: If I call md.pattern() on a simple two-column numeric data.frame, it works!
I will eventually try the clean install.

**Comment by stefvanbuuren** [comment]
Hmm, interesting. I do not see a Quartz window.

I will close because we cannot reproduce and it's likely to be related to something outside `mice`. Sorry, we cannot help, but thanks for bringing up the issue. 

Feel free to reopen if you think it's mice-related.

**Comment by gerkovink** [comment]
Reinstalling `xquartz` may help
