### ISSUE TITLE
error, mice not run

### ISSUE THREAD

**Issue by zhuoranw2021** [amices/mice#522]
When running the mice() function, I got the error below:
Error in data.frame(it = s$it, im = s$im, dep = s$dep, meth = if (is.null(meth)) s$meth else meth, : 
arguments imply differing number of rows: 0, 1

**Comment by gerkovink** [comment]
Can you provide a [reprex](https://reprex.tidyverse.org/)?

**Comment by stefvanbuuren** [comment]
Closing. No reprex.

**Comment by gmhgmh-r** [comment]
How did you solve this problem? Thank you

**Comment by stefvanbuuren** [comment]
We did not because we cannot reproduce
