### ISSUE TITLE
Mids object returns NA for imputed variables

### ISSUE THREAD

**Issue by CelineMarieL** [amices/mice#535]
When I use the complete(imp) function, my imputed NA values in the mids object appear with values in every data set. When I use amelia() to impute the variable, it also works. However, when I convert amelia to mids, the imputed variable which is present in the amelia object and the stacked long data set after using complete() becomes NA's again. WHat is the problem and does this influence my analysis with the with() function?

**Comment by stefvanbuuren** [comment]
Do you have a reprex? <https://reprex.tidyverse.org>

**Comment by stefvanbuuren** [comment]
Closing because no reprex.
