### ISSUE TITLE
Accidentally repeated roxygen comments

### ISSUE THREAD

**Issue by remlapmot** [amices/mice#603]
Thanks for such a great package.

When reading some of the helpfiles, I noticed that there are accidentally repeated roxygen comments in 6 places in the code:

https://github.com/amices/mice/blob/3abe3934985113a58f56a18665a4c90ca8772eee/R/ampute.continuous.R#L27

https://github.com/amices/mice/blob/3abe3934985113a58f56a18665a4c90ca8772eee/R/futuremice.R#L64

https://github.com/amices/mice/blob/3abe3934985113a58f56a18665a4c90ca8772eee/R/mice-package.R#L51

https://github.com/amices/mice/blob/3abe3934985113a58f56a18665a4c90ca8772eee/R/mice.R#L113

https://github.com/amices/mice/blob/3abe3934985113a58f56a18665a4c90ca8772eee/R/mira.R#L35

https://github.com/amices/mice/blob/3abe3934985113a58f56a18665a4c90ca8772eee/R/parlmice.R#L53

i.e., the second `#'` just needs to be deleted in each case.

**Comment by hanneoberman** [comment]
Thanks! I've created a  with your suggested changes https://github.com/amices/mice/pull/604

**Comment by remlapmot** [comment]
Thank you very much. Maybe you need to run `devtools::document()`/`roxygen2::roxygenize()` to regenerate the .Rd files and add those to the PR also.

**Comment by hanneoberman** [comment]
You're absolutely right! I thought I could just fix it in the online repo, but running it locally now. Thank you.
