### ISSUE TITLE
error in mice

### ISSUE THREAD

**Issue by mehrdad123qaderi** [amices/mice#650]
in this code:
SL.lib <- c("SL.mean")
imp.SL <- mice::mice( df_missing10, m = 5, maxit = 5,
method = "SuperLearner",
print = FALSE, SL.library = SL.lib)
i have error:
Error in names(newdata) <- sapply(1:ncol(newdata), function(n) { :
'names' attribute [2] must be the same length as the vector [0

**Comment by stefvanbuuren** [comment]
Thanks. This is not a full reprex, so please craft your code so that others can reproduce.

**Comment by stefvanbuuren** [comment]
No reprex. `Superleaner` is not a `mice` method, so the error may result from differences in implementation. Closing now.
