### ISSUE TITLE
Throws an error 

### ISSUE THREAD

**Issue by KahasseMaru** [amices/mice#654]
[MICE_3.16.0_erorr.docx](https://github.com/user-attachments/files/16281844/MICE_3.16.0_erorr.docx)

**Comment by hanneoberman** [comment]
![image](https://github.com/user-attachments/assets/2a844083-9055-4eb7-9192-534e2bba681e)
This issue is not reproducible. Could you create a [reprex](https://reprex.tidyverse.org/)?

**Comment by stefvanbuuren** [comment]
No reprex. Likely to be a problem with the data, so I am closing. Feel free to reopen if needed.
