### ISSUE TITLE
Error in terms.formula(tmp, simplify = TRUE) :    ExtractVars里的模型公式不对

### ISSUE THREAD

**Issue by XuzheWang** [amices/mice#658]
> data_low_new <- mice(data_low, m=5, method = "pmm", seed = 20240801)

 iter imp variable
  1   1  BMIError in terms.formula(tmp, simplify = TRUE) : 
  ExtractVars里的模型公式不对

The colnames of my data are character, and the error still comes up.
Need some help, thanks!

**Comment by stefvanbuuren** [comment]
Cannot reproduce. I suggest you create a [reprex](https://reprex.tidyverse.org) before we can help.
