### ISSUE TITLE
Computation of `df` by `pool()` in version 3.17.0

### ISSUE THREAD

**Issue by vincentarelbundock** [amices/mice#683]
Hi,

Thanks for your great work on `mice`!

I was wondering if a breaking change might have been introduced in the computation of `df` by the `pool()` function in version 3.17.0. Some of the tests for my `marginaleffects` package are now failing.

Consider a simple model, where the pooled `df` seems reasonable given the 32 observations in the original:

``` r
library(mice)
library(marginaleffects)

dat <- mtcars
dat$mpg[c(1, 4, 6, 8)] <- NA

imp <- mice(dat, m = 5, print = FALSE, seed = 48103)
fits <- with(imp, glm(am ~ hp + wt, family = binomial))
pool(fits)$pooled$df
#> [1] 27.185 27.185 27.185
```

Now, consider the output of `avg_slopes()`, which computes average slopes based on the same model, and returns suspiciously small `df` values:

``` r
fit_fun <- function(data) {
  mod <- glm(am ~ hp + wt, family = binomial, data = data)
  slo <- avg_slopes(mod)
  return(slo)
}
dat_mi <- complete(imp, "all")
fits <- lapply(dat_mi, fit_fun)
pool(fits)$pooled$df
#> [1] 0.49995 0.49995
```

Note that the `marginaleffects` package ships with a valid `tidy()` S3 method for `avg_slopes()` output, but that it has no `df.residual()` method:

``` r
df.residual(fits[[1]])
NULL

tidy(fits[[1]])
#> # A tibble: 2 × 9
#>   term  contrast estimate std.error statistic  p.value s.value  conf.low conf.high
#>   <chr> <chr>       <dbl>     <dbl>     <dbl>    <dbl>   <dbl>     <dbl>     <dbl>
#> 1 hp    dY/dX     0.00161  0.000572      2.82 4.83e- 3    7.69  0.000491   0.00273
#> 2 wt    dY/dX    -0.360    0.0571       -6.29 3.12e-10   31.6  -0.472     -0.248
```

**Comment by stefvanbuuren** [comment]
Why do you think it is related to a breaking change in `mice 3.17.0`? 

The only change made in the last year was to export some `mice::df.residual.xxx()` functions.

**Comment by vincentarelbundock** [comment]
> Why do you think it is related to a breaking change in mice 3.17.0?

Because the same code I posted above generates very different results (higher DF) in `mice` 3.16.0, and my unit tests started failing in late November when 3.17.0 was released.

Sorry, I should have been clearer about that.

``` r
packageVersion("mice")
#> [1] '3.16.0'

library(mice)
library(marginaleffects)
dat <- mtcars
dat$mpg[c(1, 4, 6, 8)] <- NA
imp <- mice(dat, m = 5, print = FALSE, seed = 48103)
fits <- with(imp, glm(am ~ hp + wt, family = binomial))
fit_fun <- function(data) {
  mod <- glm(am ~ hp + wt, family = binomial, data = data)
  slo <- avg_slopes(mod)
  return(slo)
}
dat_mi <- complete(imp, "all")
fits <- lapply(dat_mi, fit_fun)
pool(fits)$pooled$df
#> [1] 28.179 28.179
```
